version: '3.8'

services:
  app:
    restart: always
    image: "auen-backend:${VERSION}"
    ports:
      - "989:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]